spring:
  datasource:
    url: jdbc:mysql://10.197.150.121:3306/mp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  type-aliases-package: com.itheima.mp.domain.po
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

knife4j: # knife4j swagger配置
  enable: true # 是否开启swagger
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: 1257811052@qq.com
    concat: wxl
    url: https://github.com/Wangcasc
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.mp.controller
